version: '3.6'
services:
  homeassistant:
    container_name: homeassistant
    image: "homeassistant/home-assistant:2024.6"
    depends_on:
      localai:
        condition: service_healthy
    volumes:
      - ./volumes/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
#    ports:
#      - "8123:8123"
    network_mode: host

#  #VSCode
#  vscode:
#    container_name: vscode
#    image: codercom/code-server
#    volumes:
#      # Set <project dir> to the directory you want to open in VS Code.
#      - ./volumes:/config
#      # <vs code config> should point to a local dir where vs code stores its data.
#      - ./volumes/vscode:/home/coder/.local/share/code-server
#    ports:
#      - "8443:8080"
#    command: code-server --auth none --disable-telemetry /config
#    restart: unless-stopped
#    network_mode: host
  
  #Mosquitto
  mosquitto:
    container_name: mqtt
    image: eclipse-mosquitto
#    ports:
#      - "1883:1883"
#      # This port is for Webhooks
#      - "9001:9001"
    volumes:
      - ./volumes/mosquitto/config:/mosquitto/config
      - ./volumes/mosquitto/data:/mosquitto/data
      - ./volumes/mosquitto/log:/mosquitto/log
    network_mode: host

  #ESPHome 
  esphome:
    container_name: esphome
    image: esphome/esphome
    ports:
      - "6052:6052"
    volumes:
      # Update PATH_TO_YOUR_CONFIG, the :rw gives the container Read/Write access
      - ./volumes/esphome/config:/config:rw
      # Use local time for logging timestamps
      - /etc/localtime:/etc/localtime:ro
    # You do have to map a serial port here. Determine your port and uncomment.
    #devices:
    #  - /dev/ttyAMC0:/dev/ttyAMC0
    restart: always
    network_mode: host

  #LocalAI
  localai:
    # See https://localai.io/basics/getting_started/#container-images for
    # a list of available container images (or build your own with the provided Dockerfile)
    # Available images with CUDA, ROCm, SYCL
    # Image list (quay.io): https://quay.io/repository/go-skynet/local-ai?tab=tags
    # Image list (dockerhub): https://hub.docker.com/r/localai/localai
    container_name: localai
    image: localai/localai:v2.4.0-ffmpeg-core
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/readyz" ]
      interval: 1m
      timeout: 60m
      retries: 5
#    ports:
#      - 8081:8080
    environment:
      - MODELS_PATH=/models
      - DEBUG=true
    volumes:
      - ./volumes/localai/models:/models:cached
      - ./volumes/localai/images/:/tmp/generated/images/
    restart: always
    network_mode: host

  portainer:
    container_name: portainer
    image: portainer/portainer-ce
#    ports:
#      - "9000:9000/tcp"
    environment:
      - TZ=Europe/London
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/portainer:/data
    restart: always
    network_mode: host




