
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Text to speech
tts:
  - platform: picotts
    language: "en-US"

panel_iframe:
  portainer:
    title: "Portainer"
    url: "https://localhost:9443/#!/home"
    icon: mdi:docker
#  vscode:
#    title: "VSCode"
#    url: "http://172.22.0.6:8080/"
#    icon: mdi:microsoft-visual-studio-code
  esphome:
    title: "ESPHome"
    url: "http://localhost:6052"
    icon: mdi:chip